name = "Julia Zero2Hero"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
DualNumbers = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
DynamicalSystems = "61744808-ddfa-5f27-97ff-6e42cc95d634"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
